"""baseline_cp

Revision ID: baseline_cp
Revises: 
Create Date: 2026-08-28 08:25:22.714005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baseline_cp'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_purchase_account_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='會計科目代碼'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='會計科目名稱'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cycle_purchase_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False, comment='關聯類型：request | po | receiving | payment | summary（2026-08-09 新增，用於彙整單的 Ragic 拋轉／取消拋轉）'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment="關聯單據 id（軟關聯，依 document_type 對應不同表）。⚠️ document_type='summary' 的例外：拋轉是對「一整個週期＋期別＋公司範圍」的批次動作，沒有單一主鍵，這裡放 cycle_id，真正的識別是 document_no（拋轉批次號 CPSUM-...）"),
    sa.Column('document_no', sa.String(length=30), nullable=False, comment='關聯單號快照（列表顯示用，不必額外 join）'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='事件類型：backfill(補填) | overdue(逾期) | shortage(缺貨) | substitute(替代品) | receiving_variance(驗收差異) | payment_variance(請款差異) | unsummarize(退回彙整，2026-08-09 新增，由 cycle_purchase_summary_service.unsummarize_request() 觸發) | revert_to_summary(採購單退回彙整單) | ragic_push(拋轉 Ragic) | ragic_push_cancel(取消拋轉)。前四種目前仍無觸發點。⚠️ 新增值時記得同步補 frontend AuditLog 的 EVENT_TYPE_LABEL，沒對應到的會直接顯示英文原字串。'),
    sa.Column('description', sa.Text(), nullable=False, comment='事件說明'),
    sa.Column('operator_user_id', sa.String(length=36), nullable=True, comment='操作人員（portal.db users.id，軟關聯）'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作人員姓名快照'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='原始值（文字快照，依事件類型內容不同）'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='變更後值（文字快照，依事件類型內容不同）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_purchase_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_code', sa.String(length=30), nullable=False, comment='週期代碼'),
    sa.Column('cycle_name', sa.String(length=100), nullable=False, comment='週期名稱'),
    sa.Column('frequency', sa.String(length=20), nullable=False, comment='頻率：monthly | biweekly | bimonthly | custom'),
    sa.Column('open_rule', sa.String(length=200), nullable=True, comment='開放規則說明（如：每月第幾日）'),
    sa.Column('close_rule', sa.String(length=200), nullable=True, comment='截止規則說明（如：開放後 N 天）'),
    sa.Column('applicable_categories', sa.Text(), nullable=True, comment='適用品類（逗號分隔，對應 cycle_purchase_items.category；空值＝不限品類。2026-08-09 起真正被程式使用，見 request_service 的部門解析與可選料號篩選）'),
    sa.Column('applicable_scope', sa.Text(), nullable=True, comment='適用公司（逗號分隔，或 all／空值＝不限）。2026-08-09 語意收斂：這欄只放公司，部門改用 applicable_department_ids；改版前標籤誤植為「適用公司／部門」，但程式從來只比對公司'),
    sa.Column('applicable_department_ids', sa.Text(), nullable=True, comment='適用部門（逗號分隔的 cycle_purchase_departments.id）；**空值＝適用公司底下的全部啟用中部門**（舊資料自動相容）。2026-08-09 新增，見上方 class 註解方案 B'),
    sa.Column('excluded_item_ids', sa.Text(), nullable=True, comment='從適用品類整包中手動排除的料號（逗號分隔的 cycle_purchase_items.id）；空值＝不排除任何料號。2026-08-16 新增，是例外排除清單不是白名單，見上方 class 註解'),
    sa.Column('auto_generate', sa.Boolean(), nullable=False, comment='是否自動產生本期請購單（第一版預設人工按鈕觸發，日後可接排程）'),
    sa.Column('reminder_rule', sa.Text(), nullable=True, comment='提醒規則說明'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：active | inactive | paused'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_code')
    )
    op.create_table('cycle_purchase_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別'),
    sa.Column('dept_code', sa.String(length=30), nullable=False, comment='部門代碼'),
    sa.Column('dept_name', sa.String(length=100), nullable=False, comment='部門名稱'),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True, comment='承辦人（portal.db users.id，軟關聯）—— 2026-07-11 新增，供「待辦提醒」判斷登入者屬於哪個週採部門用'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_department_id', sa.String(length=30), nullable=True, comment='跨庫對照鍵，對應 portal.db RefDepartment.id；NULL=本地自建，同步不覆蓋不刪除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_department_id')
    )
    op.create_table('cycle_purchase_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=False, comment='集團料號（新編碼，非原公司料號）'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='品名'),
    sa.Column('spec', sa.String(length=300), nullable=True, comment='規格'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='類別（如：清潔用品／文具印刷／營業用品／工務）'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='計量單位'),
    sa.Column('default_qty', sa.Integer(), nullable=False, comment='批次預載數量'),
    sa.Column('moq', sa.Integer(), nullable=False, comment='最小訂購量 MOQ'),
    sa.Column('max_stock', sa.Integer(), nullable=True, comment='最大庫存量（僅供參考，不做消帳）'),
    sa.Column('min_stock', sa.Integer(), nullable=True, comment='最小庫存量（僅供參考，不做消帳）'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='參考單價'),
    sa.Column('default_vendor_id', sa.Integer(), nullable=True, comment='預設供應商 id（→ cycle_purchase_vendors.id，同資料庫內關聯）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('is_cycle_item', sa.Boolean(), nullable=False, comment='是否週期採購專用標記'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註（含原始資料來源說明）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('cycle_purchase_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_code', sa.String(length=30), nullable=False, comment='供應商代碼'),
    sa.Column('vendor_name', sa.String(length=200), nullable=False, comment='供應商名稱'),
    sa.Column('tax_id', sa.String(length=20), nullable=True, comment='統一編號'),
    sa.Column('contact_name', sa.String(length=50), nullable=True, comment='聯絡人'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='聯絡電話'),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='付款條件'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('source_vendor_id', sa.String(length=50), nullable=True, comment='來源廠商編號（portal.db vendors.vendor_id，VND-NNNN；NULL 表示本地自建）'),
    sa.Column('synced_at', sa.DateTime(), nullable=True, comment='最後一次自合約模組同步的時間'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    with op.batch_alter_table('cycle_purchase_vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_purchase_vendors_source_vendor_id'), ['source_vendor_id'], unique=True)

    op.create_table('cycle_purchase_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別（如：春大直／日曜天地）'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='歸屬部門；NULL＝不限部門（全公司共用，如文具用品）'),
    sa.Column('major_code', sa.String(length=5), nullable=False, comment='大分類代碼（E 工程／C 清潔／G 文具／S 營業用品）'),
    sa.Column('major_name', sa.String(length=50), nullable=False, comment='大分類名稱'),
    sa.Column('mid_code', sa.String(length=2), nullable=False, comment='中分類代碼（2 碼）'),
    sa.Column('mid_name', sa.String(length=100), nullable=False, comment='中分類名稱'),
    sa.Column('sub_code', sa.String(length=2), nullable=False, comment='細分類代碼（2 碼）'),
    sa.Column('sub_name', sa.String(length=100), nullable=True, comment='細分類名稱；NULL＝來源 Excel 未命名（類別字串只到中分類）'),
    sa.Column('category_name', sa.String(length=200), nullable=False, comment='類別顯示字串，等同 cycle_purchase_items.category 現存的值，是本表與既有料號資料的對照鍵（見檔頭說明，不隨 sub_name 改寫）'),
    sa.Column('serial_width', sa.Integer(), nullable=False, comment='流水碼位數（春大直全系列皆為 3 碼），供「取下一個料號」計算用'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註（含來源資料疑義說明）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'major_code', 'mid_code', 'sub_code', name='uq_cp_category_company_codes')
    )
    op.create_table('cycle_purchase_cost_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=30), nullable=False, comment='成本中心代碼'),
    sa.Column('cc_name', sa.String(length=100), nullable=False, comment='成本中心名稱'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_purchase_item_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別（如：日曜天地／春大直）'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='這個料號在這家公司屬於哪個部門（2026-07-11 新增，供請購單可選料號按部門篩選用）'),
    sa.Column('original_code', sa.String(length=30), nullable=True, comment='公司原始料號（如 C0101001）'),
    sa.Column('original_name', sa.String(length=300), nullable=True, comment='公司原始品名'),
    sa.Column('original_vendor_name', sa.String(length=200), nullable=True, comment='公司原始廠商名稱（文字，追溯用）'),
    sa.Column('vendor_id', sa.Integer(), nullable=True, comment='這個料號在這家公司實際跟哪個供應商叫貨（2026-07-11 新增，供彙整單/採購單按供應商分單用；可為 NULL，因為原始資料有些列廠商欄位本來就是空的）'),
    sa.Column('original_unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='公司原始單價'),
    sa.Column('account_code_id', sa.Integer(), nullable=True, comment='這個料號在這家公司這個部門要記到哪個會計科目（2026-08-21 新增）'),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False, comment='是否已由人工確認對照正確（不可自動合併帶入）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註（如資料清理過程說明）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_code_id'], ['cycle_purchase_account_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['cycle_purchase_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['cycle_purchase_vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'company', 'department_id', name='uq_cp_item_mapping_item_company_dept')
    )
    op.create_table('cycle_purchase_pos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_no', sa.String(length=30), nullable=False, comment='採購單號（系統產生，如 PO-202607-0001）'),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=30), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.String(length=36), nullable=True, comment='採購人員（portal.db users.id，軟關聯）'),
    sa.Column('buyer_name', sa.String(length=100), nullable=True, comment='採購人員姓名快照'),
    sa.Column('expected_date', sa.Date(), nullable=True, comment='預計到貨日'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='採購總金額，明細加總，系統維護'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：draft | issued | partial_received | received | cancelled（partial_received/received 由驗收單送出後系統自動重算，不可透過 PUT /pos/{id}/status 人工指定）'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle_purchase_cycles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['cycle_purchase_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_no')
    )
    with op.batch_alter_table('cycle_purchase_pos', schema=None) as batch_op:
        batch_op.create_index('uq_cp_po_active_cycle_period_company_vendor', ['cycle_id', 'period_label', 'company', 'vendor_id'], unique=True, sqlite_where=sa.text("status != 'cancelled'"))

    op.create_table('cycle_purchase_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_no', sa.String(length=30), nullable=False, comment='請款單號（系統產生，如 PAY-202607-0001）'),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False, comment='發票號碼'),
    sa.Column('invoice_date', sa.Date(), nullable=False, comment='發票日期'),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='發票金額'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：draft | submitted | paying | paid'),
    sa.Column('amount_diff_reason', sa.Text(), nullable=True, comment='分攤金額加總與發票金額不同時的說明（送出時檢查，不同時必填）'),
    sa.Column('processor_user_id', sa.String(length=36), nullable=True, comment='財務處理人員（portal.db users.id，軟關聯）'),
    sa.Column('processor_name', sa.String(length=100), nullable=True, comment='財務處理人員姓名快照'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['cycle_purchase_pos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_no')
    )
    op.create_table('cycle_purchase_receiving',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiving_no', sa.String(length=30), nullable=False, comment='驗收單號（系統產生，如 RC-202607-0001）'),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.String(length=36), nullable=True, comment='驗收人員（portal.db users.id，軟關聯）'),
    sa.Column('receiver_name', sa.String(length=100), nullable=True, comment='驗收人員姓名快照'),
    sa.Column('received_date', sa.Date(), nullable=False, comment='實際到貨／驗收日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：draft | completed | discrepancy（completed/discrepancy 由送出時依明細差異自動判定，不可人工指定）'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['cycle_purchase_pos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiving_no')
    )
    op.create_table('cycle_purchase_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.String(length=30), nullable=False, comment='請購單號（系統產生，2026-07-17 起格式為 PR-YYYY-MM-NNN，如 PR-2026-07-001，3 位流水號每月重新起算；改版前的舊資料仍是 PR-YYYYMM-NNNN 格式，不回溯改寫）'),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=30), nullable=False, comment='期別標籤，2026-07-17 起由系統在建立當下自動蓋章為建立月份的「YYYY-MM」，使用者不能修改；供之後彙整單把同一期各部門需求合併用'),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別（快照自部門主檔）'),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='請購總金額（明細加總，系統維護）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='改版前的狀態機殘留欄位（draft|submitted|approved|rejected），2026-07-17 起不再有業務邏輯讀寫這個欄位，只留給改版前的歷史資料顯示用；新資料一律固定寫 draft，實際可不可以編輯看的是is_closed／period_label，不是這個欄位'),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=True, comment='填寫人（portal.db users.id，軟關聯）'),
    sa.Column('submitted_by_name', sa.String(length=100), nullable=True, comment='填寫人姓名快照'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='建立時間快照（沿用舊欄位名稱，2026-07-17 起沒有「送出」這個動作了）'),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True, comment='[改版前歷史欄位，2026-07-17 起停止寫入] 簽核人'),
    sa.Column('approved_by_name', sa.String(length=100), nullable=True, comment='[改版前歷史欄位，2026-07-17 起停止寫入] 簽核人姓名快照'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='[改版前歷史欄位，2026-07-17 起停止寫入]'),
    sa.Column('reject_reason', sa.Text(), nullable=True, comment='[改版前歷史欄位，2026-07-17 起停止寫入] 退回原因'),
    sa.Column('is_summarized', sa.Boolean(), server_default='0', nullable=False, comment='是否已被某次「產生彙整」動作納入過，避免重複計入數量'),
    sa.Column('summary_batch_no', sa.String(length=40), nullable=True, comment='納入的彙整批次號（對應這次產生彙整時系統產生的批次編號）'),
    sa.Column('summarized_at', sa.DateTime(), nullable=True, comment='被納入彙整的時間'),
    sa.Column('unsummarized_by_user_id', sa.String(length=36), nullable=True, comment='退回彙整的操作人（portal.db users.id，軟關聯）'),
    sa.Column('unsummarized_by_name', sa.String(length=100), nullable=True, comment='退回彙整的操作人姓名快照'),
    sa.Column('unsummarized_at', sa.DateTime(), nullable=True, comment='最近一次從彙整單退回的時間；退回不會動 is_closed，只是把 is_summarized 改回 False 讓它重新出現在可彙整清單'),
    sa.Column('unsummarize_reason', sa.Text(), nullable=True, comment='最近一次退回彙整的原因（退回時必填）'),
    sa.Column('is_closed', sa.Boolean(), server_default='0', nullable=False, comment='是否已關閉（關閉後不能再新增/編輯明細，也不能再修改請購單本身）'),
    sa.Column('closed_by_user_id', sa.String(length=36), nullable=True, comment='關閉人（portal.db users.id，軟關聯）'),
    sa.Column('closed_by_name', sa.String(length=100), nullable=True, comment='關閉人姓名快照'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='關閉時間'),
    sa.Column('close_batch_no', sa.String(length=40), nullable=True, comment='關閉批次號（"全部關閉"或"選擇請購單關閉"同一次動作的請購單共用同一個批次號）'),
    sa.Column('reopened_by_user_id', sa.String(length=36), nullable=True, comment='重新開啟人（portal.db users.id，軟關聯）'),
    sa.Column('reopened_by_name', sa.String(length=100), nullable=True, comment='重新開啟人姓名快照'),
    sa.Column('reopened_at', sa.DateTime(), nullable=True, comment='最近一次重新開啟的時間；重新開啟不會清掉 closed_* 欄位，那些是保留的關閉歷史紀錄，is_closed 才是目前真正的狀態'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cycle_purchase_cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle_purchase_cycles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    with op.batch_alter_table('cycle_purchase_requests', schema=None) as batch_op:
        batch_op.create_index('ix_cp_request_cycle_period_dept', ['cycle_id', 'period_label', 'department_id'], unique=False)

    op.create_table('cycle_purchase_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=30), nullable=False, comment='期別標籤，同請購單'),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別'),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部門別（2026-07-16 新增，來自請購單的 department_id）。NULL 代表 2026-07-16 之前產生的歷史彙整列，未拆分部門'),
    sa.Column('item_mapping_id', sa.Integer(), nullable=True, comment='該公司該料號的對照列（取得供應商／單價用）'),
    sa.Column('vendor_id', sa.Integer(), nullable=True, comment='供應商（來自料號對照表 vendor_id，可能為 NULL——原始資料廠商欄位空的情況，此時無法轉採購單，需先到料號對照表補上供應商）'),
    sa.Column('item_code', sa.String(length=30), nullable=False, comment='料號快照'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='品名快照'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='單位快照'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='單價快照（來自該公司料號對照表）'),
    sa.Column('demand_qty', sa.Integer(), nullable=False, comment='需求總量（各已核准請購單明細加總，系統計算）'),
    sa.Column('adjusted_qty', sa.Integer(), nullable=False, comment='調整量（採購人員可調整，預設＝需求總量）'),
    sa.Column('adjust_reason', sa.Text(), nullable=True, comment='調整原因（調整量≠需求總量時必填）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='狀態：draft | converted'),
    sa.Column('po_id', sa.Integer(), nullable=True, comment='轉採購單後回填'),
    sa.Column('ragic_push_batch_no', sa.String(length=40), nullable=True, comment='拋轉批次號（同一次拋轉動作共用，如 CPSUM-202607-日曜天地-0001）'),
    sa.Column('ragic_pushed', sa.Boolean(), nullable=False, comment='是否已拋轉到 Ragic'),
    sa.Column('ragic_record_id', sa.String(length=60), nullable=True, comment='Ragic 端回填的單號／記錄 ID（目前 Ragic「匯總請購單」表單尚未建立，現階段為 stub 串接，此欄位可能是暫時性假值，見 cycle_purchase_ragic_push.py）'),
    sa.Column('ragic_pushed_at', sa.DateTime(), nullable=True, comment='拋轉成功時間'),
    sa.Column('ragic_push_error', sa.Text(), nullable=True, comment='拋轉失敗時的錯誤訊息'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle_purchase_cycles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['cycle_purchase_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_mapping_id'], ['cycle_purchase_item_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['cycle_purchase_pos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['cycle_purchase_vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'period_label', 'company', 'item_id', 'department_id', name='uq_cp_summary_cycle_period_company_item_dept')
    )
    op.create_table('cycle_purchase_payment_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False, comment='公司別（快照自採購單，僅供報表顯示用）'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部門（系統依原始請購資料自動回溯；NULL 代表系統無法自動歸屬，需要財務人員手動指定）'),
    sa.Column('cost_center_id', sa.Integer(), nullable=True, comment='成本中心（沿用原始請購單選的成本中心，可能為 NULL）'),
    sa.Column('account_code_id', sa.Integer(), nullable=True, comment='會計科目（沿用原始請購明細選的會計科目，可能為 NULL）'),
    sa.Column('suggested_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='系統試算值（建立當下計算，之後不再變動，供追溯對照）'),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='實際分攤金額，預設＝試算值，財務人員可調整'),
    sa.Column('adjust_reason', sa.Text(), nullable=True, comment='調整原因（allocated_amount ≠ suggested_amount 時必填）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_code_id'], ['cycle_purchase_account_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cycle_purchase_cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['cycle_purchase_departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['cycle_purchase_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_purchase_payment_receivings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('receiving_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['cycle_purchase_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiving_id'], ['cycle_purchase_receiving.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiving_id', name='uq_cp_payment_receiving_once')
    )
    op.create_table('cycle_purchase_po_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False, comment='來源彙整列'),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=False, comment='料號快照'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='品名快照'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='單位快照'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='單價快照（來自彙整列）'),
    sa.Column('ordered_qty', sa.Integer(), nullable=False, comment='訂購數量（＝彙整列的調整量）'),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, comment='小計＝單價×數量，系統維護'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['cycle_purchase_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['cycle_purchase_pos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['cycle_purchase_summary.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id', 'item_id', name='uq_cp_po_item')
    )
    op.create_table('cycle_purchase_request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_mapping_id', sa.Integer(), nullable=True, comment='採用哪一筆公司料號對照的單價'),
    sa.Column('account_code_id', sa.Integer(), nullable=True, comment='會計科目快照（2026-08-21 起由 cycle_purchase_item_mappings.account_code_id 自動帶入，請購單畫面不再顯示；欄位本身保留，付款分攤仍讀這裡）'),
    sa.Column('item_code', sa.String(length=30), nullable=False, comment='料號快照'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='品名快照'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='單位快照'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='單價快照（來自該公司料號對照表）'),
    sa.Column('request_qty', sa.Integer(), nullable=False, comment='請購數量'),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, comment='小計＝單價×數量（系統維護）'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_code_id'], ['cycle_purchase_account_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['cycle_purchase_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_mapping_id'], ['cycle_purchase_item_mappings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['cycle_purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'item_id', name='uq_cp_request_item')
    )
    op.create_table('cycle_purchase_receiving_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiving_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False, comment='對應的採購明細行'),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='冗餘存一份料號 id，方便進貨數量報表直接查詢不必多層 join'),
    sa.Column('item_code', sa.String(length=30), nullable=False, comment='料號快照'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='品名快照'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='單位快照'),
    sa.Column('ordered_qty', sa.Integer(), nullable=False, comment='採購明細訂購數量快照'),
    sa.Column('previously_received_qty', sa.Integer(), nullable=False, comment='這張驗收單之前，這個採購明細行累計已驗收數量快照（建立本列時計算，供顯示與追溯用）'),
    sa.Column('received_qty', sa.Integer(), nullable=False, comment='本次驗收數量'),
    sa.Column('is_final_for_item', sa.Boolean(), nullable=False, comment='這個料號是否驗收完結（不會再有後續驗收）。True 才會在送出時計算差異；多數情況一次到齊，預設 True。'),
    sa.Column('variance_qty', sa.Integer(), nullable=True, comment='差異數量＝累計已驗收數量（含本次）－訂購數量。只有 is_final_for_item=True 的列，送出時才會計算；非最後一次驗收的列維持 NULL（分批到貨中途不算差異）。'),
    sa.Column('variance_reason', sa.Text(), nullable=True, comment='差異原因（variance_qty ≠ 0 時必填）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['cycle_purchase_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_item_id'], ['cycle_purchase_po_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_id'], ['cycle_purchase_receiving.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiving_id', 'po_item_id', name='uq_cp_receiving_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycle_purchase_receiving_items')
    op.drop_table('cycle_purchase_request_items')
    op.drop_table('cycle_purchase_po_items')
    op.drop_table('cycle_purchase_payment_receivings')
    op.drop_table('cycle_purchase_payment_allocations')
    op.drop_table('cycle_purchase_summary')
    with op.batch_alter_table('cycle_purchase_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_cp_request_cycle_period_dept')

    op.drop_table('cycle_purchase_requests')
    op.drop_table('cycle_purchase_receiving')
    op.drop_table('cycle_purchase_payments')
    with op.batch_alter_table('cycle_purchase_pos', schema=None) as batch_op:
        batch_op.drop_index('uq_cp_po_active_cycle_period_company_vendor', sqlite_where=sa.text("status != 'cancelled'"))

    op.drop_table('cycle_purchase_pos')
    op.drop_table('cycle_purchase_item_mappings')
    op.drop_table('cycle_purchase_cost_centers')
    op.drop_table('cycle_purchase_categories')
    with op.batch_alter_table('cycle_purchase_vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_purchase_vendors_source_vendor_id'))

    op.drop_table('cycle_purchase_vendors')
    op.drop_table('cycle_purchase_items')
    op.drop_table('cycle_purchase_departments')
    op.drop_table('cycle_purchase_cycles')
    op.drop_table('cycle_purchase_audit_logs')
    op.drop_table('cycle_purchase_account_codes')
    # ### end Alembic commands ###
